services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 8001:9090
    links:
      - app:app.localhost

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: pass
      GF_SECURITY_ADMIN_USER: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - 8002:3000
    depends_on:
      - prometheus
